# Generated by Django 5.0.3 on 2024-03-06 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ticketing.category",
            ),
        ),
    ]
