# Generated by Django 5.0.3 on 2024-03-07 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0005_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[(3, "Low"), (2, "Medium"), (1, "High")],
                db_index=True,
                default=2,
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["priority", "title"], name="ticketing_t_priorit_b4d7ff_idx"
            ),
        ),
    ]
