# Generated by Django 5.0.3 on 2024-03-09 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0008_remove_ticket_assigned_group_team_category_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="follow_up_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_ups",
                to="ticketing.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="If a team is selected, new tickets will automatically assigned to this team.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ticketing.team",
            ),
        ),
    ]
