# Generated by Django 5.0.3 on 2024-03-11 00:06

import ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0010_fileattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileattachment",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=ticketing.models.ticket_directory_path
            ),
        ),
    ]
