# Generated by Django 5.0.3 on 2024-03-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0012_seed_mailtemplates"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="access_non_category_tickets",
            field=models.BooleanField(default=False),
        ),
    ]
