# Generated by Django 5.0.3 on 2024-03-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0013_team_access_non_category_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="readonly_access",
            field=models.BooleanField(default=False),
        ),
    ]
