# Generated by Django 5.0.3 on 2024-03-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_googlessouser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="googlessouser",
            old_name="user",
            new_name="paw_user",
        ),
    ]
