# Generated by Django 5.0.3 on 2024-03-10 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_user_googlessouser_paw_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googlessouser",
            name="id",
        ),
        migrations.AlterField(
            model_name="googlessouser",
            name="paw_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
