# Generated by Django 5.0.3 on 2024-03-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_googlessouser_id_alter_googlessouser_paw_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French"), ("de", "German")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("content", models.TextField()),
            ],
        ),
    ]
